stages:
  - test
  - build
  - deploy

.nodejs:
  image: node:16
  before_script:
    - yarn install --cache-folder .yarn
  cache:
    key: 'JS-$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
      - .yarn
    policy: pull-push

test:
  extends: .nodejs
  stage: test
  needs: []
  script:
    - yarn test

build:
  extends: .nodejs
  stage: build
  needs: []
  script:
    - yarn build
  artifacts:
    paths:
      - web-build
      - web-server

include:
  - project: 'Tymek/CI'
    file: '/.dockerize.yml'
