image: node:16
before_script:
  - yarn install --cache-folder .yarn

test:
  stage: test
  cache:
    paths:
    - node_modules/
    - .yarn

stages:
  - test
  - build
  - deploy

test:
  stage: test
  needs: []
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - web-build
      - web-server

include:
  - project: 'Tymek/CI'
    file: '/.dockerize.yml'
