stages:
  - build
  - deploy

.nodejs:
  image: node:16
  before_script:
    - yarn install --cache-folder .yarn || yarn install --cache-folder .yarn

build:
  stage: build
  extends: .nodejs
  needs: []
  script:
    - yarn test
    - yarn build
  artifacts:
    paths:
      - ./packages/app/web-build
      - ./packages/admin/out
      - ./packages/backend/dist
      - ./packages/database/lib

include:
  - project: 'Tymek/CI'
    file: '/.dockerize.yml'
