version: '3.8'
services:
  backend:
    image: registry.gitlab.com/tymek/momentum:latest
    labels:
      - traefik.enable=true
      - traefik.http.services.momentum.loadbalancer.server.port=3000
      - traefik.http.routers.momentum-web.service=momentum
      - traefik.http.routers.momentum-web.rule=Host(`${DOMAIN:-momentum.scrlk.pl}`)
      - traefik.http.routers.momentum-web.entrypoints=web
      - traefik.http.routers.momentum-web.middlewares=momentum-https
      - traefik.http.middlewares.momentum-https.redirectscheme.scheme=https
      - traefik.http.routers.momentum-websecure.service=momentum
      - traefik.http.routers.momentum-websecure.rule=Host(`${DOMAIN:-momentum.scrlk.pl}`)
      - traefik.http.routers.momentum-websecure.entrypoints=websecure
      - com.ouroboros.enable=true
    networks:
      - wan
      - lan
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}'
      HASURA_ACTION_SECRET: '${HASURA_ACTION_SECRET:-secret}'

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
    networks:
      - lan

  hasura:
    image: '${HASURA_IMAGE:-hasura/graphql-engine:v2.0.0-alpha.10.cli-migrations-v3}'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
      HASURA_GRAPHQL_DEV_MODE: 'false'
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET:-admin}'
      HASURA_GRAPHQL_AUTH_HOOK: '${HASURA_GRAPHQL_AUTH_HOOK:-http://backend:3000/api/auth-webhook}'
      HASURA_ACTION_ENDPOINT: '${HASURA_ACTION_ENDPOINT:-http://backend:3000/api/actions}'
      HASURA_ACTION_SECRET: '${HASURA_ACTION_SECRET:-secret}'
    labels:
      - traefik.enable=true
      - traefik.http.services.momentum-hasura.loadbalancer.server.port=8080
      - traefik.http.routers.momentum-hasura-web.service=momentum-hasura
      - traefik.http.routers.momentum-hasura-web.rule=Host(`${API_DOMAIN:-api.momentum.scrlk.pl}`)
      - traefik.http.routers.momentum-hasura-web.entrypoints=web
      - traefik.http.routers.momentum-hasura-web.middlewares=momentum-hasura-https
      - traefik.http.middlewares.momentum-hasura-https.redirectscheme.scheme=https
      - traefik.http.routers.momentum-hasura-websecure.service=momentum-hasura
      - traefik.http.routers.momentum-hasura-websecure.rule=Host(`${API_DOMAIN:-api.momentum.scrlk.pl}`)
      - traefik.http.routers.momentum-hasura-websecure.entrypoints=websecure
      - com.ouroboros.enable=true
    networks:
      - lan
      - wan

networks:
  lan:
    external: false
  wan:
    external: true
