version: '3.8'
services:
  server:
    command: yarn dev
    ports:
      - '3000:3000'

  hasura:
    ports:
      - '8080:8080'
      - '8081:8081'
    environment:
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: webhook-log

networks:
  lan:
    external: false
  wan:
    external: false
